"""1 column renamed

Revision ID: 9e4233bbf41e
Revises: 8c94199d3c50
Create Date: 2026-06-25 14:39:53.903463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4233bbf41e'
down_revision: Union[str, Sequence[str], None] = '8c94199d3c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_oder_product_variant','user_oder_product_variant_quantity',new_column_name='user_order_product_variant_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_oder_product_variant','user_order_product_variant_quantity',new_column_name='user_oder_product_variant_quantity')
    # ### end Alembic commands ###
