"""add table zone and zone_distance

Revision ID: eaec444d2bbb
Revises: d8348170ed66
Create Date: 2026-06-23 09:36:48.114748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaec444d2bbb'
down_revision: Union[str, Sequence[str], None] = 'd8348170ed66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_table('zone_distance',
    sa.Column('zone_id_1', sa.Integer(), nullable=False),
    sa.Column('zone_id_2', sa.Integer(), nullable=False),
    sa.Column('zone_distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id_1'], ['zone.zone_id'], ),
    sa.ForeignKeyConstraint(['zone_id_2'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('zone_id_1', 'zone_id_2'),
    )
    op.execute("INSERT INTO zone VALUES (1,'default')")
    op.add_column('location', sa.Column('zone_id', sa.Integer(), nullable=False,server_default='1'))
    op.create_foreign_key(None, 'location', 'zone', ['zone_id'], ['zone_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'zone_id')
    op.drop_table('zone_distance')
    op.drop_table('zone')
    # ### end Alembic commands ###
