"""add column description and base price to product

Revision ID: 7292c324b53d
Revises: 7b4e24990bfb
Create Date: 2026-06-19 14:05:31.748076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7292c324b53d'
down_revision: Union[str, Sequence[str], None] = '7b4e24990bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_description', sa.String(length=1000), nullable=True))
    op.add_column('product', sa.Column('product_base_price', sa.Float(), nullable=False,server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_base_price')
    op.drop_column('product', 'product_description')
    # ### end Alembic commands ###
