"""add table product_variant and its relations

Revision ID: d8348170ed66
Revises: 7292c324b53d
Create Date: 2026-06-22 13:17:53.363337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd8348170ed66'
down_revision: Union[str, Sequence[str], None] = '7292c324b53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_size', sa.String(), nullable=False),
    sa.Column('product_variant_color', sa.String(), server_default='Blanc', nullable=False),
    sa.Column('product_variant_price', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('product_variant_id'),
    sa.CheckConstraint("product_variant_size in ('XXS','XS','S','M','L','XL','XXL','XXXL')",name="ck_product_variant_size")
    )
    op.add_column('stock', sa.Column('product_variant_id', sa.Integer(),autoincrement=False, nullable=False))
    op.drop_constraint(op.f('stock_pkey'), 'stock', type_='primary')
    op.create_primary_key('stock_pkey','stock',['product_variant_id', 'location_id'])
    op.drop_constraint(op.f('stock_product_id_fkey'), 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'product_variant', ['product_variant_id'], ['product_variant_id'])
    op.drop_column('stock', 'product_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('stock_pkey'), 'stock', type_='primary')
    op.create_primary_key('stock_pkey','stock',['product_id', 'location_id'])
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key(op.f('stock_product_id_fkey'), 'stock', 'product', ['product_id'], ['product_id'])
    op.drop_column('stock', 'product_variant_id')
    op.drop_table('product_variant')
    # ### end Alembic commands ###
