"""1 table renamed

Revision ID: af780698a75c
Revises: 5e98abc8e2a1
Create Date: 2026-06-25 11:57:07.772447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af780698a75c'
down_revision: Union[str, Sequence[str], None] = '5e98abc8e2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('location_oder_product_variant','location_order_product_variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('location_order_product_variant','location_oder_product_variant')

    # ### end Alembic commands ###
