"""1 table renamed

Revision ID: 8c94199d3c50
Revises: af780698a75c
Create Date: 2026-06-25 14:14:27.328361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c94199d3c50'
down_revision: Union[str, Sequence[str], None] = 'af780698a75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('transfert_oder_product_variant','transfert_order_product_variant')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('transfert_order_product_variant','transfert_oder_product_variant')

    # ### end Alembic commands ###
