"""Add unique constraint on name of product and location

Revision ID: 7b4e24990bfb
Revises: 132f130bcc9b
Create Date: 2026-06-18 14:43:10.432643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4e24990bfb'
down_revision: Union[str, Sequence[str], None] = '132f130bcc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['location_name'])
    op.create_unique_constraint(None, 'product', ['product_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
