"""1 table renamed

Revision ID: 06a2a9624bb3
Revises: d5ceb831a7fe
Create Date: 2026-06-25 16:07:18.592320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a2a9624bb3'
down_revision: Union[str, Sequence[str], None] = 'd5ceb831a7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_oder_product_variant','user_order_product_variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_order_product_variant','user_oder_product_variant')

    # ### end Alembic commands ###
