"""Add table vendor and table catalog

Revision ID: f7b5f7f81f07
Revises: eaec444d2bbb
Create Date: 2026-06-23 15:52:33.030004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b5f7f81f07'
down_revision: Union[str, Sequence[str], None] = 'eaec444d2bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False,server_default='1'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name')
    )
    op.create_table('catalog',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('catalog_selling_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.product_variant_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('product_variant_id', 'vendor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog')
    op.drop_table('vendor')
    # ### end Alembic commands ###
