"""1 column renamed

Revision ID: d5ceb831a7fe
Revises: 9e4233bbf41e
Create Date: 2026-06-25 14:44:02.889640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ceb831a7fe'
down_revision: Union[str, Sequence[str], None] = '9e4233bbf41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfert_order_product_variant','transfert_oder_product_variant_quantity',new_column_name='transfert_order_product_variant_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfert_order_product_variant','transfert_order_product_variant_quantity',new_column_name='transfert_oder_product_variant_quantity')

    # ### end Alembic commands ###
