"""Handling of product movement + 1 stock column renamed

Revision ID: 5e98abc8e2a1
Revises: f7b5f7f81f07
Create Date: 2026-06-24 14:10:50.216499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e98abc8e2a1'
down_revision: Union[str, Sequence[str], None] = 'f7b5f7f81f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.Column('order_status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_status_id')
    )
    #TODO#insert default value in order_status
    op.execute("INSERT INTO order_status (order_status_name) VALUES ('PENDING')")
    op.execute("INSERT INTO order_status (order_status_name) VALUES ('SHIPPED')")
    op.execute("INSERT INTO order_status (order_status_name) VALUES ('DELIVERED')")
    op.execute("INSERT INTO order_status (order_status_name) VALUES ('ABORTED')")

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_firstname', sa.String(length=50), nullable=False),
    sa.Column('user_lastname', sa.String(length=50), nullable=False),
    sa.Column('user_birthday', sa.DateTime(), nullable=False),
    sa.Column('user_mail', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )

    op.create_table('location_order',
    sa.Column('location_order_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.order_status_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('location_order_id')
    )

    op.create_table('transfert_order',
    sa.Column('transfert_order_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.order_status_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('transfert_order_id')
    )

    op.create_table('user_order',
    sa.Column('user_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.Column('user_order_promotion', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.order_status_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_order_id')
    )

    op.create_table('location_oder_product_variant',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('location_order_id', sa.Integer(), nullable=False),
    sa.Column('location_order_product_variant_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_order_id'], ['location_order.location_order_id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.product_variant_id'], ),
    sa.PrimaryKeyConstraint('product_variant_id', 'location_order_id')
    )

    op.create_table('transfert_oder_product_variant',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('transfert_order_id', sa.Integer(), nullable=False),
    sa.Column('transfert_oder_product_variant_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.product_variant_id'], ),
    sa.ForeignKeyConstraint(['transfert_order_id'], ['transfert_order.transfert_order_id'], ),
    sa.PrimaryKeyConstraint('product_variant_id', 'transfert_order_id')
    )
    op.create_table('user_oder_product_variant',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('user_order_id', sa.Integer(), nullable=False),
    sa.Column('user_oder_product_variant_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.product_variant_id'], ),
    sa.ForeignKeyConstraint(['user_order_id'], ['user_order.user_order_id'], ),
    sa.PrimaryKeyConstraint('product_variant_id', 'user_order_id')
    )

    op.alter_column('stock','quantity',new_column_name='stock_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_quantity','quantity',new_column_name='stock')
    op.drop_table('user_oder_product_variant')
    op.drop_table('transfert_oder_product_variant')
    op.drop_table('location_oder_product_variant')
    op.drop_table('user_order')
    op.drop_table('transfert_order')
    op.drop_table('location_order')
    op.drop_table('user')
    op.drop_table('order_status')
    # ### end Alembic commands ###
